In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [2]:
df = pd.read_csv('spam.csv',encoding='latin-1')
df.head(5)

,label,text,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [3]:
df.drop_duplicates(inplace = True)

In [4]:
df.shape

(5169, 5)

In [5]:
df.isnull().sum()

label            0
text             0
Unnamed: 2    5126
Unnamed: 3    5159
Unnamed: 4    5164
dtype: int64

In [6]:
df.head(5)

,label,text,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [23]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.shape
df.head()

KeyError: "['Unnamed: 2' 'Unnamed: 3' 'Unnamed: 4'] not found in axis"

In [22]:
nltk.download('stopwords')
df.head()

[nltk_data] Downloading package stopwords to C:\Users\Utsav
[nltk_data]     Suthar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
def process_text(text):
    nopunc= [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean_words

In [11]:
df['text'].head().apply(process_text)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: text, dtype: object

In [12]:
message4= 'hello world hello hello world play'
message5= 'test test test test one hello'
print(message4)
print()

from sklearn.feature_extraction.text import CountVectorizer 
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()
print(bow4.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer 
message_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(message_bow, df['label'],test_size = 0.2, random_state = 0)

In [15]:
df.shape

(5169, 2)

In [16]:
message_bow.shape

(5169, 11304)

In [17]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train)

In [18]:
print(classifier.predict(x_train))
print(y_train.values)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']
['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']

In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))
print()
print('confusion_Matrix: \n',(y_train,pred))
print()
print('Accuracy: ',accuracy_score(y_train, pred))

              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3631
        spam       0.98      0.98      0.98       504

    accuracy                           1.00      4135
   macro avg       0.99      0.99      0.99      4135
weighted avg       1.00      1.00      1.00      4135


confusion_Matrix:
 (3794    ham
4290    ham
2603    ham
3452    ham
3132    ham
       ...
5307    ham
3455    ham
1708    ham
2730    ham
2871    ham
Name: label, Length: 4135, dtype: object, array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4'))

Accuracy:  0.9954050785973397

In [20]:
print(classifier.predict(x_test))
print(y_test.values)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']
['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))
print()
print('confusion_Matrix: \n',(y_test,pred))
print()
print('Accuracy: ',accuracy_score(y_test, pred))

              precision    recall  f1-score   support

         ham       0.99      0.96      0.97       885
        spam       0.80      0.93      0.86       149

    accuracy                           0.96      1034
   macro avg       0.89      0.94      0.92      1034
weighted avg       0.96      0.96      0.96      1034


confusion_Matrix:
 (1851    ham
2375    ham
2743    ham
3324    ham
3995    ham
       ...
2237    ham
4368    ham
3046    ham
4263    ham
2674    ham
Name: label, Length: 1034, dtype: object, array(['ham', 'ham', 'ham', ..., 'ham', 'ham', 'ham'], dtype='<U4'))

Accuracy:  0.9555125725338491